### ISSUE TITLE
Piepen nach einschalten und keine Funktion

### ISSUE THREAD

**Issue by Noelle88** [larsmm/hoverboard-firmware-hack-bbcar#2]
Hallo Lars.

Ich habe versucht dein Programm zu flashen (Hardwareanpassung ist auch erfolgt), aber scheinbar klappt es nicht richtig.

Der fehler den ich gleich beschreibe ist auch beim Versuch mit "hoverboard-firmware-hack-FOC" aufgetreten.
Desweiteren habe ich Ich hoffe du kannst mir weiter helfen.

Ich habe das Programm in Visual Studio Code wie folgt angepasst:
Zeile       Wert
18.          39.8 V
21.          10 Zellen
67.          350
68.          1100
69.          350
70.          1100

und kompiliere - Von dort uploaden konnte ich leider schon nicht, weil mir mein ST-Link V2 dort nicht angezeigt wird und eine Fehlermeldung kommt, dass keine Verbindung aufgebaut werden konnte.

Ich habe dann in der STM32 Link Utility die Sperre aufgehoben und die erstellte .bin datei geflasht. Danach wird sie wird im "Device Memory" auch angezeigt, daher gehe ich davon aus, dass der Upload geklappt hat.

Nun zur Fehlerbeschreibung (mit Versorgungsspannung ca. 41V aufgeladenener Akku)

Sobald ich den "EIN"-Taster drücke beginnt ein piepen "tüdelüt,tüdelüt,tüdelüt", usw.
Wenn ich in der STM32 Link Utility die Verbindung trenne kommt ein "tüdeldididi" und eine rote LED leuchtet -> nach ca. 25 sec. geht die Platine wieder in den Zustand, wie beim "EIN" tasten.

In beiden Situationen ist keinerlei Funktion festzustellen. Selst das "AUS" tasten geht nicht.
Ich hoffe du kannst mit meiner Fehlerbeschreibung etwas anfangen und mir evtl. weiter helfen.
Auf den Github-Seiten von NiklasFauth und EmanuelFeru habe ich leider keine Lösung finden können.

Beste Grüße aus dem Harz, Niels

**Comment by larsmm** [comment]
Hallo Niels,

das ist hier das falsche Projekt. Meine Firmware basiert momentan noch auf der nicht-FOC Firmware von Niklas. Die verhält sich schon deutlich anders als die FOC Firmware von Emanuel. Z. B. hat Emanuels Version verschiedene Fehlererkennungen für z. b. falsch angeschlossene oder defekte Motoren. Hast du beide Motoren angeschlossen? Ist dein Input Mode korrekt konfiguriert? Vielleicht ist das eine Notabschaltung weil die Inputwerte ausserhalb des gültigen Bereiches liegen. Die Motoren werden am Anfang auch nur scharf geschaltet wenn die Input Werte einmal in Nullposition standen. Schalte mal das serial debug ein und schau ob deine Inputs funktionieren. Manche Platinen sind auch einfach defekt. Es wäre schon hilfreich zu wissen ob sich eine andere Platine genauso verhält.

**Comment by Noelle88** [comment]
Erstmal Danke für deine schnelle Antwort.
Da habe ich mich wohl etwas schwammig ausgedrückt, entschuldige.
Ich arbeite mit deiner Software. Ich habe nur die FOC-Firmware einmal aufgespielt, um zu schauen ob sich der Fehler dort genau so verhält, was er auch tut.

Die Motoren sind alle okay und ich habe alle Komponenten zum testen angeschlossen. Den Input habe ich auch auf ADC gestellt.
Ich konnte heute leider erst meinen Seriell-Adapter finden, damit ich nachforschen konnte -.-

Die Werte passten nicht, wie du schon vermutet hattest.
Mit dem Calibration MODE habe ich die Werte MIN / MAY auf mein Setup angepasst.
Mit den Werten      ADCx_MIN   -100    / ADCx_MAX 212 kam ich im Debugger auf:
adc1_flt:0  adc2_flt:0  acc_cmd:0.32  brk_cmd:0.32

Hier war dann allerdings das Problem, dass trotzdem beide Potis als betätigt erkannt wurden.
Weil die Werte ja nicht  ins negative gehen dürfen, habe ich ADCx_MIN 0, später ADCx_MAX auf 1500 gestellt.

Nach dem übertragen, beende ich die Verbing des ST Link zum Mainboard -> das normale tüdelüt und zwei Piepse für den Mode 2 ertönen. Der Debugger wirft folgendes aus:

> (Infos zur Firmware under der Modi)
> . . . . 
> waiting for poti release...
> potis released
> enabling motors, entering main loop
> adc1_flt:90  adc2_flt:89  acc_cmd:0.06  brk_cmd:0.06  speed:0    . . . 
> Power button down, waiting for release...
> Power button up: power off

Wenn ich den Powerknopf los lasse Piept es ein paar mal kurz und die Platine geht aus.
Soweit also okay, abgesehen von den Werten die nicht zur Kalibrierung passen.
Wenn ich den Knopf nun aber zum einschalten wieder betätige, ertönt das fehlerhafte §tüdelüt,tüdelüt,tüdelüt" in Endlosschleife und nichts geht mehr.

Ich habe noch eine weitere Platine bespielt, diese ließ sich aber nicht seriell verbinden -> ISt wohl defekt
Eine Hoverboard, welches noch zusammengebaut ist und funktioniert werde ich die Tage ausschlachten und es mit der Hardware noch einmal versuchen. Ich berichte dann noch mal.

Bis dahin erstmal und ein schönes Wocheneden.
