### ISSUE TITLE
Hello, teachers, I come from China, I have a question to ask

### ISSUE THREAD

**Issue by mouixong** [larsmm/hoverboard-firmware-hack-bbcar#3]
I in an accidental opportunity discovered that your this firmware is really too good, is extremely good, specially that 4 gears may shift gears I like it very much, but I found a problem in the process of using it, that is, it will shut down automatically after releasing the throttle, but my voltage is normal, and the battery is just full

**Comment by mouixong** [comment]
But I do not seem to have this problem with other firmware  I hope that teachers can give me pointers  Teachers, do you use Wechat?You can add my wechat if you can   290970116

**Comment by larsmm** [comment]
There are a lot of emergency power off conditions. For example poti-out-of-range. Did you calibrate potis and battery voltage?

**Comment by mouixong** [comment]
The voltage has been calibrated, but how to calibrate the potentiometer? Is there a tutorial on this?

**Comment by larsmm** [comment]
There is a new, much better version of this firmware: https://github.com/larsmm/hoverboard-firmware-hack-FOC-bbcar
Please use the new one and follow the calibration instructions in the readme.

**Comment by mouixong** [comment]
I use two wheels to drive, which part of this firmware should be modified?

---Original---
From: ***@***.***&gt;
Date: Thu, Sep 2, 2021 22:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [larsmm/hoverboard-firmware-hack-bbcar] Hello, teachers, I come from China, I have a question to ask (#3)




 
There is a new, much better version of this firmware: https://github.com/larsmm/hoverboard-firmware-hack-FOC-bbcar
 Please use the new one and follow the calibration instructions in the readme.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
