### ISSUE TITLE
Front/ back with one mid rest pot (joystick). Possible?

### ISSUE THREAD

**Issue by kris86k** [larsmm/hoverboard-firmware-hack-bbcar#4]
Hi.
I need use in ADC mode (bobby car) mid rest pot (its cheap joystick) only for front and back, no need stearing. Min value is 0, medium ~2000 and max 4400.
Its possible to use one pot for front and back ride?

I see this function in EmanuelFeru but your firmware is better for me.

Thanks,
Kris

**Comment by larsmm** [comment]
No, my bobby car firmware is not made for that. You would have to rewrite most of the code. I think it is best to start with EmanuelFeru firmware.

**Comment by kris86k** [comment]
I use his firmware but I have problem to reduce speed in torque mode. This is only mode what is possible to use for me.
Meaby u can tell me how to reduce speed in torque mode?
