### ISSUE TITLE
what

### ISSUE THREAD

**Issue by LONG-9527** [larsmm/hoverboard-firmware-hack-bbcar#6]
![f552ad88cf438765963626bf3ca69f5](https://user-images.githubusercontent.com/127329914/224048709-fb04ba27-8b5c-4390-9dac-22743d8d50e7.png)

**Comment by larsmm** [comment]
You are on the deprecated old repo. Please read the readme.

The new one: https://github.com/larsmm/hoverboard-firmware-hack-FOC-bbcar
